services:
  nginx:
    image: openresty/openresty:alpine
    container_name: nginx
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./docker/nginx/waf:/etc/nginx/waf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
    networks:
      - laravel

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1G
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_POST_MAX_SIZE: 1G
      PHP_MAX_EXECUTION_TIME: 300
      PHP_MEMORY_LIMIT: 512M
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - laravel

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http nginx:80
    environment:
      NGROK_AUTHTOKEN: "tokennya"
    networks:
      - laravel

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/gitlab-runner:/etc/gitlab-runner
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
  minio_data:
